language: ruby
rvm:
  - 2.2
install:
  - bundle install
  - curl -L -o packer.zip https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip && unzip -d bin packer.zip
script:
  - PATH=$(pwd)/bin:$PATH bundle exec rake
